package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseScene;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Scene extends BaseScene<Scene> {
	public static final Scene dao = new Scene().dao();
}
