package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrderType(java.lang.Integer orderType) {
		set("orderType", orderType);
		return (M)this;
	}
	
	public java.lang.Integer getOrderType() {
		return getInt("orderType");
	}

	public M setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsId() {
		return getInt("goodsId");
	}

	public M setActivityId(java.lang.Integer activityId) {
		set("activityId", activityId);
		return (M)this;
	}
	
	public java.lang.Integer getActivityId() {
		return getInt("activityId");
	}

	public M setAgencyId(java.lang.Integer agencyId) {
		set("agencyId", agencyId);
		return (M)this;
	}
	
	public java.lang.Integer getAgencyId() {
		return getInt("agencyId");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setAgencyPrice(java.lang.String agencyPrice) {
		set("agencyPrice", agencyPrice);
		return (M)this;
	}
	
	public java.lang.String getAgencyPrice() {
		return getStr("agencyPrice");
	}

}
