package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInvitation<M extends BaseInvitation<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setInvitationTitle(java.lang.String invitationTitle) {
		set("invitationTitle", invitationTitle);
		return (M)this;
	}
	
	public java.lang.String getInvitationTitle() {
		return getStr("invitationTitle");
	}

	public M setInvitationContent(java.lang.String invitationContent) {
		set("invitationContent", invitationContent);
		return (M)this;
	}
	
	public java.lang.String getInvitationContent() {
		return getStr("invitationContent");
	}

	public M setInviterName(java.lang.String inviterName) {
		set("inviterName", inviterName);
		return (M)this;
	}
	
	public java.lang.String getInviterName() {
		return getStr("inviterName");
	}

	public M setInviterId(java.lang.Integer inviterId) {
		set("inviterId", inviterId);
		return (M)this;
	}
	
	public java.lang.Integer getInviterId() {
		return getInt("inviterId");
	}

}
