package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActivity<M extends BaseActivity<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setActivityName(java.lang.String activityName) {
		set("activityName", activityName);
		return (M)this;
	}
	
	public java.lang.String getActivityName() {
		return getStr("activityName");
	}

	public M setActivityContent(java.lang.String activityContent) {
		set("activityContent", activityContent);
		return (M)this;
	}
	
	public java.lang.String getActivityContent() {
		return getStr("activityContent");
	}

	public M setActivityPrice(java.lang.String activityPrice) {
		set("activityPrice", activityPrice);
		return (M)this;
	}
	
	public java.lang.String getActivityPrice() {
		return getStr("activityPrice");
	}

	public M setAcencyId(java.lang.String acencyId) {
		set("acencyId", acencyId);
		return (M)this;
	}
	
	public java.lang.String getAcencyId() {
		return getStr("acencyId");
	}

}
