package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseAgency;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Agency extends BaseAgency<Agency> {
	public static final Agency dao = new Agency().dao();
}
