package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseInvitation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Invitation extends BaseInvitation<Invitation> {
	public static final Invitation dao = new Invitation().dao();
}
