package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAgency<M extends BaseAgency<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAgencyName(java.lang.String agencyName) {
		set("agencyName", agencyName);
		return (M)this;
	}
	
	public java.lang.String getAgencyName() {
		return getStr("agencyName");
	}

	public M setAgencyPhone(java.lang.String agencyPhone) {
		set("agencyPhone", agencyPhone);
		return (M)this;
	}
	
	public java.lang.String getAgencyPhone() {
		return getStr("agencyPhone");
	}

}
