package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGoodsName(java.lang.String goodsName) {
		set("goodsName", goodsName);
		return (M)this;
	}
	
	public java.lang.String getGoodsName() {
		return getStr("goodsName");
	}

	public M setGoodsPrice(java.math.BigDecimal goodsPrice) {
		set("goodsPrice", goodsPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getGoodsPrice() {
		return get("goodsPrice");
	}

	public M setGoodsImg(java.lang.String goodsImg) {
		set("goodsImg", goodsImg);
		return (M)this;
	}
	
	public java.lang.String getGoodsImg() {
		return getStr("goodsImg");
	}

}
